name: Durability
version: 1.0.0
main: lad.obsidian.durability.Durability
author: Obsidianlad
description: Check tool durability.

permissions:
  durability.check:
    default: true
    description: Is able to check tool durability.

commands:
  durability:
    description: Check tool durability
    usage: /durability
  uses:
    description: Check tool durability
    usage: /uses
